---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs-tcp
      port: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: mountd-tcp
      port: 20048
      protocol: TCP
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    role: nfs-server