---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  labels:
    lalbeName: labelValue
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
      default_type text/plain;
      location / {
        return 200 '$hostname\nOK\n';
      }
    }